name: 'GSA/ansible-os-win-2019'
description: 'Ansible Role for Windows Server 2019'
license: cc0-1.0
openSourceProject: 1
governmentWideReuseProject: 1
tags:
    - open-source
    - opensource
    - devsecops
    - ansible
contact:
    email: ise-guides@gsa.gov
